name: 🤖 Update Profile

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: profile-update
  cancel-in-progress: true

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install deps
        run: npm install axios luxon dotenv

      - name: Run updater
        run: node scripts/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push
        run: |
          git config user.name "RafaelaSommer"
          git config user.email "camilaerafaelagoncalves@hotmail.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "🤖 profile auto update"
            git push origin main --force
          fi
